import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate } from 'react-router-dom';
import { Container, Box, Button, Typography, Paper, Grid } from '@mui/material';
import { useAuth } from '../contexts/AuthContext';
export const HomePage = () => {
    const navigate = useNavigate();
    const { isAuthenticated } = useAuth();
    return (_jsxs(Container, { maxWidth: "lg", sx: { py: 8 }, children: [_jsxs(Box, { sx: { textAlign: 'center', mb: 6 }, children: [_jsx(Typography, { variant: "h2", component: "h1", gutterBottom: true, sx: { fontWeight: 'bold', mb: 2 }, children: "Welcome to InvestHub" }), _jsx(Typography, { variant: "h5", color: "textSecondary", paragraph: true, children: "Connect startups with investors and make your vision a reality" })] }), isAuthenticated ? (_jsxs(Grid, { container: true, spacing: 3, sx: { mt: 2 }, children: [_jsx(Grid, { item: true, xs: 12, sm: 6, children: _jsxs(Paper, { sx: { p: 3, textAlign: 'center' }, children: [_jsx(Typography, { variant: "h6", gutterBottom: true, children: "Browse Startups" }), _jsx(Typography, { variant: "body2", color: "textSecondary", paragraph: true, children: "Discover innovative startups looking for investment" }), _jsx(Button, { variant: "contained", onClick: () => navigate('/startups'), fullWidth: true, children: "View Startups" })] }) }), _jsx(Grid, { item: true, xs: 12, sm: 6, children: _jsxs(Paper, { sx: { p: 3, textAlign: 'center' }, children: [_jsx(Typography, { variant: "h6", gutterBottom: true, children: "My Profile" }), _jsx(Typography, { variant: "body2", color: "textSecondary", paragraph: true, children: "Manage your startup or investor profile" }), _jsx(Button, { variant: "contained", onClick: () => navigate('/profile'), fullWidth: true, children: "Go to Profile" })] }) })] })) : (_jsxs(Box, { sx: { textAlign: 'center', mt: 4 }, children: [_jsx(Typography, { variant: "body1", paragraph: true, children: "Sign up or log in to get started" }), _jsxs(Box, { sx: { display: 'flex', gap: 2, justifyContent: 'center' }, children: [_jsx(Button, { variant: "contained", size: "large", onClick: () => navigate('/register'), children: "Sign Up" }), _jsx(Button, { variant: "outlined", size: "large", onClick: () => navigate('/login'), children: "Log In" })] })] }))] }));
};
export default HomePage;
